_base_: '../_base_/cityscapes.yml'

batch_size: 1
iters: 80000

model:
  type: ENCNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 19
  channels: 512
  enable_se_loss: True
  align_corners: False
  add_lateral: False

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: SELoss
  coef: [1, 0.4, 0.2]
